steps:
  # Create Artifact Registry repository if it doesn't exist
  - id: "setup-repository"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts repositories describe backend \
          --location=${_REGION} \
          --project=${PROJECT_ID} &>/dev/null || \
        gcloud artifacts repositories create backend \
          --repository-format=docker \
          --location=${_REGION} \
          --project=${PROJECT_ID}

  # Configure Docker authentication for Artifact Registry
  - id: "configure-docker"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["auth", "configure-docker", "${_REGION}-docker.pkg.dev"]

  # Build the container image
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args: 
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/backend/${REPO_NAME}:${COMMIT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/backend/${REPO_NAME}:latest"
      - "."

  # Push the container image to Artifact Registry
  - id: "push-image"
    name: "gcr.io/cloud-builders/docker"
    args: 
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/backend/${REPO_NAME}"

  # Deploy container image to Cloud Run
  - id: "deploy-service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${REPO_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/backend/${REPO_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "1"
      - "--memory"
      - "512Mi"
      - "--concurrency"
      - "500"
      - "--set-env-vars"
      - "MYSQL_PRISMA_URL=${_MYSQL_PRISMA_URL}"

substitutions:
  _REGION: "us-central1"

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET